---
# This docker-compose file will start some containers that act like VMs in a VPC
services:
  kc1:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kc1
    container_name: kc1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kc2:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kc2
    container_name: kc2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kc3:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kc3
    container_name: kc3
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kafka1:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kafka1
    container_name: kafka1
    ports:
     - "9092:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kafka2:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kafka2
    container_name: kafka2
    ports:
     - "9093:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kafka3:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kafka3
    container_name: kafka3
    ports:
     - "9094:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kafka4:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kafka4
    container_name: kafka4
    ports:
     - "9095:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kafka5:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kafka5
    container_name: kafka5
    ports:
     - "9096:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kafka6:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kafka6
    container_name: kafka6
    ports:
     - "9097:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  cc:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: cc
    container_name: cc
    ports:
     - "9021:9021"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host